# Generated by Django 4.2.10 on 2024-03-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=255)),
                ('i_price', models.CharField(max_length=20)),
                ('i_desc', models.CharField(max_length=255)),
                ('i_imgage', models.ImageField(upload_to='item_image/')),
            ],
        ),
    ]
